/*
** globales.c for decode in /home/bondot_e/rendu/projets_perso/decode_toolkit
** 
** Made by etienne bondot
** Login   <bondot_e@epitech.net>
** 
** Started on  Wed Jun  5 11:48:17 2013 etienne bondot
** Last update Wed Jun  5 21:30:42 2013 etienne bondot
*/

#include "decode.h"

t_option option[] = {
  {"-c", &cesar},
  {"-v", &vigenere},
  {0, 0}
};

char	*vigenere_table[] = {
  "ABCDEFGHIJKLMNOPQRSTUVWXYZ",
  "BCDEFGHIJKLMNOPQRSTUVWXYZA",
  "CDEFGHIJKLMNOPQRSTUVWXYZAB",
  "DEFGHIJKLMNOPQRSTUVWXYZABC",
  "EFGHIJKLMNOPQRSTUVWXYZABCD",
  "FGHIJKLMNOPQRSTUVWXYZABCDE",
  "GHIJKLMNOPQRSTUVWXYZABCDEF",
  "HIJKLMNOPQRSTUVWXYZABCDEFG",
  "IJKLMNOPQRSTUVWXYZABCDEFGH",
  "JKLMNOPQRSTUVWXYZABCDEFGHI",
  "KLMNOPQRSTUVWXYZABCDEFGHIJ",
  "LMNOPQRSTUVWXYZABCDEFGHIJK",
  "MNOPQRSTUVWXYZABCDEFGHIJKL",
  "NOPQRSTUVWXYZABCDEFGHIJKLM",
  "OPQRSTUVWXYZABCDEFGHIJKLMN",
  "PQRSTUVWXYZABCDEFGHIJKLMNO",
  "QRSTUVWXYZABCDEFGHIJKLMNOP",
  "RSTUVWXYZABCDEFGHIJKLMNOPQ",
  "STUVWXYZABCDEFGHIJKLMNOPQR",
  "TUVWXYZABCDEFGHIJKLMNOPQRS",
  "UVWXYZABCDEFGHIJKLMNOPQRST",
  "VWXYZABCDEFGHIJKLMNOPQRSTU",
  "WXYZABCDEFGHIJKLMNOPQRSTUV",
  "XYZABCDEFGHIJKLMNOPQRSTUVW",
  "YZABCDEFGHIJKLMNOPQRSTUVWX",
  "ZABCDEFGHIJKLMNOPQRSTUVWXY",
  "\0"
};
